<?php

namespace Prueba\ComunBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacturaProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaProductoRepository extends EntityRepository
{
}
